### ISSUE TITLE
Only work after visiting index

### ISSUE THREAD

**Issue by SuperCuber** [RandomSeeded/HeroStream#2]
The website only works properly if you visit the index page first. To reproduce the issue open a new tab and type url of specific hero, you should see the monstercat stream (from what I understood its the default one)

After that go to main page and click on the hero name and you will see that there actually is a stream on that hero.

**Comment by RandomSeeded** [comment]
I'll check it out :)

**Comment by RandomSeeded** [comment]
@SuperCuber this should be fixed, thanks for raising it
